### ISSUE TITLE
Web版HelpのCopyボタンが生成されていない

### ISSUE THREAD

**Issue by tukinami** [lost-nd-xxx/LilyNovelPlayer#1]
私の環境だと、Web版Helpである https://lost-nd-xxx.github.io/LilyNovelPlayer/hint.html と https://lost-nd-xxx.github.io/LilyNovelPlayer/tags.html において、Copyボタンが生成されていません。
(Windows10, FirefoxとChromeで確認)

恐らく、関数を即時実行しているため、`document`が読み込まれる前に実行され、`pre`タグが認識されていないことが原因だと思います。
(ゴーストマスカレード6版では~~html~~`body`に直接記述なされていたため、~~html~~`body`のパースが終わってから実行されていたのだと思います)(追記: 誤記修正しました)

このプロジェクトのhtmlについてライセンスが分からなかったため、forkはしなかったのですが、`docs/src/script.js`の1行目からある即時実行関数を、

```js
document.addEventListener('DOMContentLoaded',() => {
    // ここに内容
   // `d`を`document`に変更して下さい
});
```
(追記: 注意書きを追記しました)

と変更するとCopyボタンが生成されたことを報告いたします。

素敵なプロジェクトありがとうございます。応援しております。

**Comment by lost-nd-xxx** [comment]
ご報告と応援ありがとうございます！　修正しました。
